apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-v02
  labels: 
    app: employees 
    version: v2
spec:
  selector:
    matchLabels:
       app: employees
       version: v2
  replicas: 1
  template:
    metadata:
      labels:
        app: employees
        version: v2
    spec:
      containers:
      - name: app-deployment
        image: 475376810255.dkr.ecr.us-east-1.amazonaws.com/assignment1-mainrepo:v0.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env: 
        - name: DBHOST
          value: 10.244.0.27
        - name: DBUSER
          value: root
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR
          value: blue
        - name: DBPWD
          value: assign2
