apiVersion: v1
kind: Service
metadata:
  name: myappsvc-v02
  labels:
    name: myassignmentpod
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30000
  selector:
     app: employees
     version: v2 
