apiVersion: v2
kind: Service
metadata:
  name: myappsvc
  labels:
    name: myassignmentpod
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30000
  selector:
     name: myassignmentpod 
     app: my-app
 
