apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: myassignmentpod 
    app: my-app
spec:
  containers:
    - name: app
      image: 475376810255.dkr.ecr.us-east-1.amazonaws.com/assignment1-mainrepo
      ports:
        - containerPort: 3306
      env: 
     - name: DBHOST
       value: mysqlsvc.sqldb.svc.cluster.local
     - name: DBUSER
       value: root
     - name: DBPORT
       value: "3306"
     - name: APP_COLOR
       value: blue
     - name: DBPWD
       value: assign2