apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    name: myassignmentpod
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8080
    nodePort: 30001
  selector:
     app: employees
     version: v1
 
