apiVersion: v1
kind: Service
metadata:
  name: mysqlsvc
  labels:
    name: myassignmentpod 
    app: my-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: employees
    version: v1