apiVersion: v1
kind: Service
metadata:
  name: myappsvc
  labels:
    name: myassignmentpod
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
     name: myassignmentpod 
     app: my-app
 
