apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: dbreplicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      labels:
        name: myassignmentpod 
        app: my-app
  template:
    metadata:
      labels:
       labels:
          name: myassignmentpod 
          app: my-app
    spec:
      containers:
        - name: my-container
          image: 475376810255.dkr.ecr.us-east-1.amazonaws.com/assignment1-datarepo:v0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: assign2
